import bpy


# Generic BB2 "Global" variables
curFrame = 1
filePath = ""
activeTag = ""              # the active/selected model
projectLastFrame = 1        # Used in multi-pdb context to calculate offset Frame for GE Simulation


# PDB-MODELS-related variables (no chains-related variables)
pdbID = 0
pdbIDmodelsDictionary = {}  # Key: pdb_ID;  value: a dictionary containing all the models of the current (ID) PDB


# CHAINS-related variables
chainCount = 0          # PDB import preview: chains number in PDB
importChainID = []      # PDB import preview: chains names in PDB
importChainOrderList = []   # PDB import preview: chains to be imported
mainChainCacheDict = {}        # a cache to that contains only mainchain atoms for the various PDBid (key)
mainChainCache_NucleicDict = {}
mainChainCache_Nucleic_FilteredDict = {}
chainCacheDict = {}            # a cache to that contains all non-H atoms for the various PDBid (key)
chainCache_NucleicDict = {}
ChainModels = {}            # cache to contain model of chains and atoms belonging to chains


# EP-related variables
epOBJ = []                # holds a list of object generated by the EP visualization
curveCount = 0            # a counter for EP curves
dxData = []                # list[n] of Potential data
dimension = []            # list[3] of dx grid dimension
origin = []                # list[3] of dx grid origin
dxCache = {}                # cache to speed up vertexColor mapping
maxCurveSet = 4


dic_lipo_materials = {}
